### ISSUE TITLE
December 2019 - content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Enterprise-ready-cloud#34]
This workshop is scheduled for a content update.  Please review the current workshop and provide update suggestions for review.  Thanks!

**Comment by paulopsgility** [comment]
Proposed updates

WDS

- Preferred solution – Cost Management
- Remove all references to Cloudyn. Cloudyn is not available for new commercial subscriptions, only for CSPs. As the customer scenario focuses on EA, it shouldn’t be there.

HOL

- Update all cmdlets to use the Az* cmdlet set (e.g. Task 2.3 uses the old cmdlets)
- Possible adds
- Working with the resource graph to create an inventory dashboard - https://docs.microsoft.com/en-us/azure/governance/resource-graph/first-query-portal#import-example-resource-graph-explorer-dashboards
- Interact with Change History (Preview) - https://docs.microsoft.com/en-us/azure/governance/policy/how-to/determine-non-compliance#change-history-preview
- Creating a budget using ACM - https://docs.microsoft.com/en-us/azure/cost-management/tutorial-acm-create-budgets

**Comment by rdendtler** [comment]
WDS

- The example structure of the company is very decentralized (everything is essentially duplicated between each BU)...This is fine..however, throughout the case study, we talk about the Cloud Adoption team being centralized/shared.  Because things like networking, security, policy and others may be "shared services" it may be good to add the concept of "Shared Services" to the overall diagram.  It will make students think a bit deeper about what they are designing and reflects real-world
- The cost center categories of "Development and Test, Production, Support Services, and Infrastructure" probably need to remove "infrastructure".. I know this is a nit-pick, but I don't understand the difference between Infrastructure and the other components (unless it's things like "network"...)... If it's network, etc, then it would be "Support Services"... In my opinion
- We may want to include "Monitoring" as a baseline item here too.. Deciding early on about how to handle Log Analytics, "core monitoring", etc, is a good thing.  Would keep it simple, but things like Network watcher and Service monitoring would make sense to me.
- Update References.. Need to remove scaffold article (been incorporate into CAF Ready)
- I recognize that there is a bit of "art" here, but I don't agree with the "Proposed Solution" Management group hierarchy.  We can discuss, but essentially it's too deep and setup as it is, it means there are a lot of duplications of policies (since most Production environments will have the same policies throughout the company)...  
- Update the "Proposed Solution" to use the new INITIATIVE for Resource Tagging.  In general, I recommend we talk a bit more about Initiatives too, since it simplifies adding Policies over time...

HOL

- Recommend for Management Groups:  Create a GUID for Management Group ID.  Display names can always be changed but a MG ID, once created, can't. Better to just use a GUID....
- Recommend we start referencing "Initiatives" as a holder for Policies.  This makes it easier to add/remove policies from assigned subscriptions. (the initiative is always there, but the policies in it can change)
- For Testing of Policies, probably not a bad idea to have them apply a policy to examine what resources are compliant and then how to remediate.  That's a common task.

**Comment by paulopsgility** [comment]
@rdendtler Thanks for the feedback Rob. We'll incorporate that into the update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #35
